
name: Deploy LinkedIn Auto Poster

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run LinkedIn Poster
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_2: ${{ secrets.ACCESS_TOKEN_2 }}
          USER_1: ${{ secrets.USER_1 }}
          USER_2: ${{ secrets.USER_2 }}
        run: python main_v2.py
